Another new sound for 'Sounds' DA
a2stuff/a2d pull request #718
Opened 2022-11-08 17:14 UTC by frankmilliron

2022-11-08 20:58 UTC, inexorabletash requested changes

2022-11-08 20:58 UTC, inexorabletash commented on desk.acc/sounds.s
> +        ;; This routine is not relocatable & must be run from $0300(!)
No need for this comment - this is true of many of the routines.

2022-11-08 20:58 UTC, inexorabletash commented on desk.acc/sounds.s
> +        JMP     $0315      ;loop2
This can use `loop2` - SOUND_PROC defines the assembly origin for the routine as $300 so hard-coding is not necessary.

2022-11-08 20:58 UTC, inexorabletash commented on desk.acc/sounds.s
> +        JMP     $0308      ;loop1
Same - just use `loop1` here, the assembler will do the right thing.

2022-11-08 22:17 UTC, frankmilliron commented
Should be fixed now! Thanks.

2022-11-09 01:54 UTC, merged

2022-11-09 01:54 UTC, inexorabletash commented
Thanks!